services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    command: ash
    volumes:
      - .:/app
      - node-modules:/app/node_modules
    tty: true
    stdin_open: true

volumes:
  node-modules: